# Generated by Django 5.2.8 on 2026-01-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
