# Generated by Django 5.2.8 on 2026-01-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_agentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent'), ('renter', 'Renter'), ('landlord', 'Landlord')], default='buyer', max_length=10),
        ),
    ]
